version: 1.0.{build}
image: Visual Studio 2017
configuration: Release

before_build:
  - nuget restore

build:
   publish_wap: true
   
artifacts:
  - path: demoapp.zip
    name: MyApp

  - path: logs
    name: DemoApp logs
    type: zip
