version: 1.0.{build}
image: Visual Studio 2017
configuration: Release

clone_folder: c:\projects\DemoApp

platform: Any CPU

before_build:
  - nuget restore

build:
   publish_wap: true
   
artifacts: 
  - path: Deployments\DemoApp_Deployment.zip 
    name: DemoApp_Deployment
